# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/zybo-z10_workspace/Zybo-Z7-Master.xdc

# Block Designs: bd/Mydesign/Mydesign.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mydesign || ORIG_REF_NAME==Mydesign} -quiet] -quiet

# IP: bd/Mydesign/ip/Mydesign_processing_system7_0_0/Mydesign_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mydesign_processing_system7_0_0 || ORIG_REF_NAME==Mydesign_processing_system7_0_0} -quiet] -quiet

# IP: bd/Mydesign/ip/Mydesign_proc_sys_reset_0_0/Mydesign_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mydesign_proc_sys_reset_0_0 || ORIG_REF_NAME==Mydesign_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/Mydesign/ip/Mydesign_ledController_0_0/Mydesign_ledController_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mydesign_ledController_0_0 || ORIG_REF_NAME==Mydesign_ledController_0_0} -quiet] -quiet

# IP: bd/Mydesign/ip/Mydesign_buttonController_0_0/Mydesign_buttonController_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mydesign_buttonController_0_0 || ORIG_REF_NAME==Mydesign_buttonController_0_0} -quiet] -quiet

# IP: bd/Mydesign/ip/Mydesign_deBouncer_0_0/Mydesign_deBouncer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mydesign_deBouncer_0_0 || ORIG_REF_NAME==Mydesign_deBouncer_0_0} -quiet] -quiet

# IP: bd/Mydesign/ip/Mydesign_clk_wiz_0_0/Mydesign_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mydesign_clk_wiz_0_0 || ORIG_REF_NAME==Mydesign_clk_wiz_0_0} -quiet] -quiet

# XDC: bd/Mydesign/Mydesign_ooc.xdc
