# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/zybo-z10_workspace/Zybo-Z7-Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ledControler_0_0/design_1_ledControler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ledControler_0_0 || ORIG_REF_NAME==design_1_ledControler_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_buttons_0_0/design_1_buttons_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_buttons_0_0 || ORIG_REF_NAME==design_1_buttons_0_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
