# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/zybo-z10_workspace/Zybo-Z7-Master.xdc

# IP: ip/xadc_wiz_0/xadc_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xadc_wiz_0 || ORIG_REF_NAME==xadc_wiz_0} -quiet] -quiet

# XDC: ip/xadc_wiz_0/xadc_wiz_0_ooc.xdc

# XDC: ip/xadc_wiz_0/xadc_wiz_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==xadc_wiz_0 || ORIG_REF_NAME==xadc_wiz_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
